info:
  profile: config-client-prod
  
name: config-client-prod
words: hello,config-client

#food: '{cipher}2c76fe51c9f426b4f86ca08ba7b47654fdb81515108694c17bee2fffdc867766'
food: '{cipher}AQBJ3PkXqVBBU5HcKFxtfE1ClRJPHTtkIhEq/eXgs30GrIngtthBLn42ar28RpZdzGqxsWCfW28qqyqV13h6PDsviBZjNMbTW3spyiTFbLxtPHMisVANJcMHRaUTsn3yLBvf9uId3vHAxh7a5/LjWG/gkdkKtqWrKUfmmCj3lfX4rRKHvWL76Nl7rjhAPBDTmuObJXErYO0qLPZxHqRevK7BdjFA9DcRzzfDTs7dj/fQRYMdjeJjrQaOO/yFnX6SiHCCJO+NpetHkXP81x/1k0NQs1+PIDFclKFPauIe/WRZNks4zOG7t3YfADX3OExh27sIAEB1ouMG4mtGj2jIhehKBYGehoVDOwhv1pIpDNYmgp/qYkHSWZ/oDdKthoZ8kqQ='
